// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuz_P6XhAEJTt_s8TSzdgOA3b0x0wXTc',
    appId: '1:208445900766:web:fe5230452b9d3270d5ff4f',
    messagingSenderId: '208445900766',
    projectId: 'inventory-app-4e238',
    authDomain: 'inventory-app-4e238.firebaseapp.com',
    storageBucket: 'inventory-app-4e238.firebasestorage.app',
    measurementId: 'G-MZK5ZJXSXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPAMCPpHNyGxw7AqneCujATmEk8BMz8k',
    appId: '1:208445900766:android:b3930d15706878b6d5ff4f',
    messagingSenderId: '208445900766',
    projectId: 'inventory-app-4e238',
    storageBucket: 'inventory-app-4e238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2gAMooSv-xJ2V4V94c5dJZR9TFkS13lE',
    appId: '1:208445900766:ios:e59b2a6c1ba853b8d5ff4f',
    messagingSenderId: '208445900766',
    projectId: 'inventory-app-4e238',
    storageBucket: 'inventory-app-4e238.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );
}
